config/routes.rb
LoyaltyApp::Application.routes.draw do

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  namespace :api, defaults: {format:'json'} do
    namespace :v1 do
      resources :rewards

      resources :giftcards, only: [:index, :show] do
        member do
          post :redeem
        end
      end

      resources :users, only: [:index, :show] do
        member do
          post :add_points
        end
      end

      resources :stats, only: [:index]

    end
  end

  root 'pages#home'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users
end

app/models/giftcard.rb
class Giftcard < ActiveRecord::Base
  belongs_to :owner, :class_name => 'User'

  def redeem! user
    Giftcard.transaction do
      user.points += self.value
      self.owner = user
      self.save!
      user.save!
    end
  end

  def redeemed?
    !self.owner_id.nil?
  end

end

app/models/reward.rb
class Reward < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are: :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable

  before_save :ensure_authentication_token

  has_many :giftcards, :foreign_key => :owner_id
  belongs_to :company

  def name
    self.username
  end


end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::Base
  protect_from_forgery with: :null_session

  before_action :restrict_access

  #api calls should not interfere with devise's trackable, etc
  before_action :skip_trackable

  rescue_from Exception do |e|
    if Rails.env.production?
      msg = ''
    else
      msg = e.inspect
    end
    render json: msg, status: :internal_server_error
  end

  private

  def restrict_access
    authenticate_or_request_with_http_basic do |token, ignored|
      @current_user ||= User.where(:authentication_token => token).first
    end

    @current_user ||= User.where(:authentication_token => params[:auth_token]).first

    head :unauthorized unless @current_user
  end

  def admin_only
    head :unauthorized unless @current_user.try(:admin)
  end



  def skip_trackable
    request.env['devise.skip_trackable'] = true
  end

end

app/controllers/api/v1/giftcards_controller.rb
class Api::V1::GiftcardsController < Api::ApiController

  before_action :admin_only, :only => [:index]

  respond_to :json

  def index
    respond_with Giftcard.all
  end

  def show
    respond_with Giftcard.where(:code => params[:id])
  end

  def redeem
    gc = Giftcard.where(:code => params[:id]).first

    if gc and !gc.redeemed?
      gc.redeem! @current_user
      head :ok

    else
      #either non existent or already redeemed.
      head :forbidden
    end

  end

end

app/controllers/api/v1/rewards_controller.rb
class Api::V1::RewardsController < Api::ApiController

  class Reward < ::Reward
    def as_json(options = {})
      super.as_json(only: ['id', 'name', 'price'])
    end
  end

  respond_to :json

  def index
    respond_with Reward.all
  end

  def show
    respond_with Reward.find(params[:id])
  end

end

app/controllers/api/v1/stats_controller.rb
class Api::V1::StatsController < Api::ApiController

  respond_to :json

  def index
    render json: User.select(:id, :username, :points).order('points desc')
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::ApiController

class User < ::User
    def as_json(options = {})
      super.as_json(only: ['username', 'email', 'points'])
    end
  end

  respond_to :json

  def index
    respond_with User.all
  end

  def show
    respond_with User.find(params[:id])
  end

  def add_points
    u = User.find(params[:id])
    u.points += params[:amount].to_d

    if u.save
      head :ok
    else
      render json: u.errors, status: :unprocessable_entity
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for(:title) { page_title.to_s }
  end

  def yield_or_default(section, default = '')
    content_for?(section) ? content_for(section) : default
  end

  def twitterized_type(type)
    case type
      when :alert
        "alert-block"
      when :error
        "alert-error"
      when :notice
        "alert-info"
      when :success
        "alert-success"
      else
        type.to_s
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html{ lang: I18n.locale.to_s }
  %head
    %meta{ charset: 'utf-8' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0' }
    %title= yield_or_default :title, controller.action_name.titlecase
    = csrf_meta_tags
    = yield :head
    /HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>

    = stylesheet_link_tag 'application',
                          media: 'all'

    / Touch icons
    %link{ href: asset_path('apple-touch-icon.png'), rel: 'apple-touch-icon' }
    %link{ href: asset_path('apple-touch-icon-72x72.png'), rel: 'apple-touch-icon', sizes: '72x72' }
    %link{ href: asset_path('apple-touch-icon-114x114.png'), rel: 'apple-touch-icon', sizes: '114x114' }
    %link{ href: asset_path('apple-touch-icon-144x144.png'), rel: 'apple-touch-icon', sizes: '144x144' }

    /
      Le javascript
      \==================================================
    / Placed at the top of the document 'cause of turbolinks
    = javascript_include_tag 'application'

  %body
    = render 'shared/navbar'

    #main-container.container
      = render :partial => "shared/flash_messages", :locals => {:flash => flash}

      .content= yield

    #footer
      .container= render 'shared/footer'

app/views/pages/home.html.haml
- title t('hello')

%p
  &nbsp;

%p.lead.muted
  %i.icon-tags
  Rewards and Gift cards

%hr
%footer
  %p
    = link_to 'https://github.com/cxz/loyalty' do
      %i.icon-github
      Source Code: cxz/loyalty
  %p
    = link_to rails_admin_path do
      %i.icon-admin
      Admin (user: admin, password: admin123)

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  - unless message.blank?
    %div{:class => "alert #{twitterized_type(type)} fade in"}
      %button.close{'data-dismiss' => 'alert'}
        ×
      = message

app/views/shared/_navbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to Rails.application.class.parent_name, root_path, class: 'brand'